---
- name: Instalar Kind
  hosts: ["localhost"]
  connection: local
  roles:
  - name: kind

#  tasks:
#  #- shell: uname -m
#  #  ignore_errors: yes
#  #  register: unamem_result
#  #
#  #- debug: msg = "{{ unamem_result.stdout }}"
#  #
#  - shell: uname
#    ignore_errors: yes
#    register: uname_result
#
#  - name: Instalar kind
#    become: yes
#    get_url:
#      url: "https://kind.sigs.k8s.io/dl/v0.20.0/kind-{{ uname_result.stdout }}-amd64"
#      dest: /usr/local/bin/kind
#      mode: "+x"
#
