apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio-operator
  namespace: default
spec:
  releaseName: minio-operator
  targetNamespace: minio-operators
  install:
    createNamespace: true
  interval: 5m
  chart:
    spec:
      chart: operator
      #version: '4.0.x'
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: default
      interval: 1m
  values: {}
  #  replicaCount: 2
