apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio-operator
  namespace: default
spec:
  releaseName: minio-operator
  targetNamespace: minio-operators
  install:
    createNamespace: true
  interval: 1m
  chart:
    spec:
      chart: operator
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: default
      interval: 1m
  values:
    console:
      ingress:
        enabled: true
        ingressClassName: "nginx"
        labels:
          app: minio
          component: operator
          environment: dev
        annotations:
          company: xnetcorp
          cert-manager.io/cluster-issuer: selfsigned
        tls:
        - secretName: minio-operator-tls
          hosts:
          - miniocp.crossnetcorp.com
        host: miniocp.crossnetcorp.com
        path: /
        pathType: Prefix
