apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio-tenant
  namespace: default
spec:
  releaseName: minio-tenant-1
  targetNamespace: default
  install:
    createNamespace: true
  interval: 1m
  dependsOn:
  - name: minio-operator
    namespace: default
  chart:
    spec:
      chart: tenant
      version: v5.0.11
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: default
      interval: 1m
  values:
    secrets:
      name: minio-tenant-1-env-config
      accessKey: minio
      secretKey: minio123
    existingSecret:
      name: minio-tenant-1-env-config
    tenant:
      name: minio-tenant-1
      configuration:
        name: minio-tenant-1-env-config
      pools:
      - servers: 1
        name: pool-0
        volumesPerServer: 2
        size: 2Gi
        storageClassName: standard

    ingress:
      api:
        enabled: api
        ingressClassName: "nginx"
        labels:
          app: minio
          component: console
          environment: dev
        annotations:
          company: xnetcorp
          cert-manager.io/cluster-issuer: selfsigned
        tls:
        - secretName: minio-tenant-1-tls
          hosts:
          - minio.crossnetcorp.com
        host: minio.crossnetcorp.com
        path: /api
        pathType: Prefix
      console:
        enabled: true
        ingressClassName: "nginx"
        labels: { }
        annotations:
          company: xnetcorp
          cert-manager.io/cluster-issuer: selfsigned
        tls:
        - secretName: minio-tenant-1-tls
          hosts:
          - minio.crossnetcorp.com
        host: minio.crossnetcorp.com
        path: /console
        pathType: Prefix
