apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio-tenant
  namespace: minio-operator
spec:
  releaseName: minio-tenant-1
  targetNamespace: default
  install:
    createNamespace: true
  interval: 1m
  chart:
    spec:
      chart: tenant
      #version: '4.0.x'
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: default
      interval: 1m
  values:
    secrets:
      name: minio-tenant-1-env-config
      accessKey: minio
      secretKey: minio123
    existingSecret:
      name: minio-tenant-1-env-config
    tenant:
      name: minio-tenant-1
      configuration:
        name: minio-tenant-1-env-config
      pools:
        name: pool-0
        volumesPerServer: 1
        size: 2Gi
        storageClassName: standard
    ingress:
      api:
        enabled: false
        ingressClassName: ""
        labels: { }
        annotations: { }
        tls: [ ]
        host: minio.crossnetcorp.com
        path: /
        pathType: Prefix
      console:
        enabled: true
        ingressClassName: "nginx"
        labels: { }
        annotations:
          company: xnetcorp
          cert-manager.io/cluster-issuer: selfsigned
        tls:
        - secretName: vault-tls
          hosts:
          - minio.crossnetcorp.com
        host: minio.crossnetcorp.com
        path: /
        pathType: Prefix
