apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: vault-issuer-1
  namespace: default
spec:
  vault:
    server: http://vault.default:8200
    path: pki/sign/application
    auth:
      kubernetes:
        mountPath: /v1/auth/kubernetes
        role: issuer
        secretRef:
          name: issuer-token #issuer-token-lmzpj
          key: token
