apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bitpoke
  namespace: database
spec:
  interval: 5m
  chart:
    spec:
      chart: mysql-operator #mysql-operator
      version: "2.1.1" #">=4.0.0 <5.0.0"
      sourceRef:
        kind: HelmRepository
        name: bitpoke #presslabs
        #namespace: database
      interval: 1m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      remediateLastFailure: false
  values:
    replicaCount: 1
    serviceMonitor:
      enabled: false
    mysqlClustersGlobalServiceMonitor:
      enabled: false
    orchestrator:
      ingress:
        enabled: true
        className: "nginx"
        annotations:
          cert-manager.io/issuer: selfsigned
        hosts:
        - host: orchestrator.crossnetcorp.com
          paths:
          - path: /
            pathType: ImplementationSpecific
        tls:
        - secretName: orchestrator-tls
          hosts:
          - orchestrator.crossnetcorp.com
      persistence:
        enabled: true
        size: 1Gi
