- name: kubectl| Detectar Version
  get_url:
    url: https://dl.k8s.io/release/stable.txt
    dest: /tmp/k8s_release.txt

- name: kubectl| store latest
  shell: cat /tmp/k8s_release.txt
  register: k8s_version

- debug: var=k8s_version

- name: kubectl| Instalar CLI
  get_url:
    url: "https://dl.k8s.io/release/{{ k8s_version.stdout_lines[0] }}/bin/linux/amd64/kubectl"
    dest: /usr/local/bin/kubectl
    mode: "+x"
    #checksum: "https://dl.k8s.io/release/{{ k8s_version.stdout_lines[0] }}/bin/linux/amd64/kubectl.sha256"
  become: yes
