apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: partyreferencedata
  namespace: microservices
spec:
  interval: 1m
  url: https://github.com/xnet-training/partyreferencedata
  ref:
    branch: main
  ignore: |-
    # exclude all
    /*
    # include charts directory
    !/chart/
