apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: partyreferencedata
  namespace: microservices
spec:
  interval: 1m
  releaseName: partyreferencedata
  chart:
    spec:
      chart: chart
      sourceRef:
        kind: GitRepository
        name: partyreferencedata
  values:
    image:
      tag: 1.0.2
