apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jenkins
  namespace: management
spec:
  interval: 5m
  chart:
    spec:
      chart: jenkins
      #version: ">=4.0.0 <5.0.0"
      sourceRef:
        kind: HelmRepository
        name: jenkins
        namespace: management
      interval: 1m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      remediateLastFailure: false
  values:
    controller:
      ingress:
        enabled: true
        #labels: {}
        annotations:
          company: xnetcorp
          cert-manager.io/issuer: selfsigned
        ingressClassName: "nginx"
        pathType: Prefix
        activeService: true
        hosts:
          - host: jenkins.crossnetcorp.com
            paths: []
        tls:
        - secretName: jenkins-tls
          hosts:
          - jenkins.crossnetcorp.com
    # Storages 
    persistence:
      enabled: true
      size: "3Gi"
