apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: presslabs
  namespace: database
spec:
  interval: 5m
  chart:
    spec:
      chart: mysql-operator
      version: "2.1.1" #">=4.0.0 <5.0.0"
      sourceRef:
        kind: HelmRepository
        name: presslabs
        namespace: database
      interval: 1m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      remediateLastFailure: false
  values:
    serviceMonitor:
      enabled: false

     
