apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vault-token-creator-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-full-secrets-abilities
  #k8s-minimal-secrets-abilities
subjects:
- kind: ServiceAccount
  name: vault
  namespace: default #vault

