apiVersion: apps/v1
kind: Deployment
metadata: 
  name: mssql-operator
  namespace: ag1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql-operator
  template:
    metadata:
      labels:
        app: mssql-operator
    spec:
      containers:
      - name: mssql-operator
        image: mcr.microsoft.com/mssql/ha:2019-CTP2.1-ubuntu
        command:
        - /mssql-server-k8s-operator
        env:
        - name: MSSQL_K8S_NAMESPACE
          valueFrom:
            fieldRef: {fieldPath: metadata.namespace}
        image: mcr.microsoft.com/mssql/ha:2019-CTP2.1-ubuntu
      serviceAccount: mssql-operator
